#%RAML 1.0 DataType
type: object
properties:
  UNIDAD:
    type: string
    description: Tipo de Proyecto
  PROPIETARIO_DEL_CLIENTE:
    type: string
    description: Propietario del Cliente
    required: false
  TIPO_DE_CLIENTE:
    type: string
    description: Tipo de Cliente
    required: false
  RAZON_SOCIAL:
    type: string
    description: Nombre / Razón Social
    required: false
  TIPO_DE_DOCUMENTO:
    type: string
    description: Tipo de Documento
    required: false
  NUMERO_DE_DOCUMENTO:
    type: string
    description: Número de Documento
    required: false
  PROCEDENCIA:
    type: string
    description: Procedencia
    required: false
  SEGMENTO_DE_CLIENTE:
    type: string
    description: Segmento de Cliente
    required: false
  TIPO_DE_CALLE:
    type: string
    description: Tipo de Calle
    required: false
  DIRECCION:
    type: string
    description: Direccion
    required: false
  NRO_LT:
    type: string
    description: Numero LT
    required: false
  PAIS:
    type: string
    description: País
    required: false
  DEPARTAMENTO:
    type: string
    description: Departamento
    required: false
  PROVINCIA:
    type: string
    description: Provincia
    required: false
  DISTRITO:
    type: string
    description: Distrito
    required: false
  TAMANO:
    type: string
    description: Tamano
    required: false
  SECTOR:
    type: string
    description: Sector
    required: false
  ESTADO_DE_CLIENTE:
    type: string
    description: Estado de Cliente
    required: false
  PROYECTOS_PRINCIPALES:
    type: string
    description: Proyectos Principales
    required: false
  COMPETENCIA_CON_QUE_TRABAJA:
    type: string
    description: Competencia con que trabaja
    required: false
  RELACIONES_DE_EMPRESA:
    type: string
    description: Competencia  con que trabaja
    required: false
  COMENTARIOS:
    type: string
    description: Comentarios
    required: false
  TELEFONO:
    type: string
    description: Comentarios
    required: false
  CELULAR:
    type: string
    description: Celular
    required: false
  CREADO_POR:
    type: string
    description: Creado Por
    required: false
  ULTIMA_MODIFICACION_POR:
    type: string
    description: Última modificación Por
    required: false
  FECHA_DE_CREACION:
    type: string
    description: Fecha de creación
    required: false
  FECHA_DE_ULTIMA_MODIFICACION:
    type: string
    description: Fecha de última modificación
    required: false
      
  
      
  

   
      
    
  