#%RAML 1.0 NamedExample
value:
  UNIDAD: Provincias
  PROPIETARIO_DEL_CLIENTE: a
  TIPO_DE_CLIENTE: a
  RAZON_SOCIAL: a
  TIPO_DE_DOCUMENTO: a
  NUMERO_DE_DOCUMENTO: a
  PROCEDENCIA: a
  SEGMENTO_DE_CLIENTE: a
  TIPO_DE_CALLE: a
  DIRECCION: a
  NRO_LT: a
  PAIS: a
  DEPARTAMENTO: a
  PROVINCIA: a
  DISTRITO: a
  TAMANO: a
  SECTOR: a
  ESTADO_DE_CLIENTE: a
  PROYECTOS_PRINCIPALES: a
  COMPETENCIA_CON_QUE_TRABAJA: a
  RELACIONES_DE_EMPRESA: a
  COMENTARIOS: a
  TELEFONO: a
  CELULAR: a
  CREADO_POR: a
  ULTIMA_MODIFICACION_POR: a
  FECHA_DE_CREACION: a
  FECHA_DE_ULTIMA_MODIFICACION: a