#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/21d568b6-3e62-47e4-a05f-e90edebbb818/ # 
version: v2
title: unicon-clientes

types:
  Cliente: !include DataType/Cliente.raml

/clientes:
  post:
    body:
      application/json:
        type: Cliente
        examples: 
          input: !include Examples/ClienteExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Se agrego el Cliente
  put:
    body:
      application/json:
        type: Cliente
        examples: 
          input: !include Examples/ClienteExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Se modifico el Cliente

          
      

